[versions]
dgt = "2.35.+"
devauth = "1.2.1"

[plugins]
deftu = { id = "dev.deftu.gradle.tools", version.ref = "dgt" }
shadow = { id = "dev.deftu.gradle.tools.shadow", version.ref = "dgt" }
bloom = { id = "dev.deftu.gradle.tools.bloom", version.ref = "dgt" }
loom = { id = "dev.deftu.gradle.tools.minecraft.loom", version.ref = "dgt" }
ducks = { id = "dev.deftu.gradle.tools.ducks", version.ref = "dgt" }
resources = { id = "dev.deftu.gradle.tools.resources", version.ref = "dgt" }